---
- hosts: webservers
  become: true
  ignore_errors: true
  gather_facts: true
  tasks:
    - name: install package
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - wget
        - finger
        - docker