---
- hosts: webservers
  become: True
  ignore_errors: True
  tasks:
  - name: Create a user
    user:
      name: johnd
      comment: John Doe
      state: present
  - name: Create a file
    file:
      path: /tmp/ansiblefile
      state: touch
  - name: Create a directory
    file:
      path: /opt/directory_ansible
      state: directory
  - name: install apache
    package:
      name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2'}}"
      state: present
    when: ansible_distribution == 'Amazon' or ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Start apache
    service:
      name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2'}}"
      state: started
    when: ansible_distribution == 'Amazon' or ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
