---
- hosts: webservers
  become: true
  become_user: root
  gather_facts: true
  ignore_errors: true
  tasks:
    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - lsof 
        - wget 
        - passwd 
        - docker 
        - unzip 
        - java-11*
    - name: Create a directory
      file:
        path: /opt/qa/spg
        state: directory
    - name: Create a file
      file:
        path: /opt/qa/spg/spg.log
        state: touch
    - name: Start docker
      service:
        name: docker
        state: started
    - name: Enable docker
      service: 
        name: docker
        enabled: yes

